# Generated by Django 4.2.19 on 2025-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0002_userdata_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
