# Generated by Django 4.2.19 on 2025-03-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0003_userdata_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='job',
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
