# Generated by Django 4.2.19 on 2025-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0004_remove_userdata_job_userdata_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
