# Generated by Django 4.2.19 on 2025-03-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0005_qualification_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='uid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
