# Generated by Django 4.2.19 on 2025-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0009_userdata_displayed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='phone',
        ),
        migrations.AddField(
            model_name='userdata',
            name='_address',
            field=models.BinaryField(db_column='address', null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='_phone',
            field=models.BinaryField(db_column='phone', null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
