# Generated by Django 4.2.19 on 2025-04-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0010_remove_userdata_address_remove_userdata_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='blood_sugar',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='height',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='userdata',
            name='_date_of_birth',
            field=models.BinaryField(db_column='date_of_birth', null=True),
        ),
    ]
