# Generated by Django 4.2.19 on 2025-04-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0011_remove_medicalhistory_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='_blood_pressure',
            field=models.BinaryField(db_column='blood_pressure', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='_blood_sugar',
            field=models.BinaryField(db_column='blood_sugar', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='_cholesterol',
            field=models.BinaryField(db_column='cholesterol', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='_height',
            field=models.BinaryField(db_column='height', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='_notes',
            field=models.BinaryField(db_column='notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='_weight',
            field=models.BinaryField(db_column='weight', null=True),
        ),
    ]
