# Generated by Django 4.2.19 on 2025-04-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0012_medicalhistory__blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
